spring:
  application:
    name: All-Ligo_Aos

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: gemma4:latest
        temperature: 0.7

server:
  port: 8083

worker:
  base-url: http://localhost:8000


aws:
  region: ap-northeast-2
  s3:
    bucket: ${AWS_S3_BUCKET:}
    base-url: ${AWS_S3_BASE_URL:}